// Per-tool options for the image tools (09-image-tools.md). Same declarative rules as options.ts:
// no React, no `node:` imports; `showWhen` is the only logic.
import type { SelectOption, TextOption, ToolOption } from "./options";

const packaging: SelectOption = {
  id: "packaging",
  type: "select",
  label: "Deliver as",
  default: "zip",
  choices: [
    { value: "zip", label: "One ZIP archive" },
    { value: "files", label: "Separate downloads" },
  ],
  help: "Only applies when there is more than one result.",
};

const colorField = (id: string, label: string, fallback: string, help?: string): TextOption => ({
  id,
  type: "text",
  label,
  default: fallback,
  placeholder: fallback,
  help: help ?? "A hex code like #ff8800, or a name: white, black, red, blue, yellow…",
});

const quality = (fallback: number, showWhen?: ToolOption["showWhen"]): ToolOption => ({
  id: "quality",
  type: "number",
  label: "Quality",
  default: fallback,
  min: 1,
  max: 100,
  step: 1,
  unit: "%",
  help: "Used for JPG, WebP and AVIF. Lower = smaller file.",
  ...(showWhen ? { showWhen } : {}),
});

const positions = [
  { value: "top-left", label: "Top left" },
  { value: "top-center", label: "Top centre" },
  { value: "top-right", label: "Top right" },
  { value: "middle-left", label: "Middle left" },
  { value: "center", label: "Centre" },
  { value: "middle-right", label: "Middle right" },
  { value: "bottom-left", label: "Bottom left" },
  { value: "bottom-center", label: "Bottom centre" },
  { value: "bottom-right", label: "Bottom right" },
];

/** The method picker every model-capable tool shares (see apps/api/src/images/model.ts). */
const method = (builtin: string): SelectOption => ({
  id: "method",
  type: "select",
  label: "Method",
  default: "auto",
  choices: [
    { value: "auto", label: "Best available (local AI model if enabled)" },
    { value: "builtin", label: `Built-in — ${builtin}` },
    { value: "ai", label: "Local AI model only" },
  ],
  help: "AI models run on your own computer and are set up in Settings. The built-in method always works offline.",
});

const strength: SelectOption = {
  id: "strength",
  type: "select",
  label: "Strength",
  default: "medium",
  choices: [
    { value: "light", label: "Light" },
    { value: "medium", label: "Medium" },
    { value: "strong", label: "Strong" },
  ],
};

const fitModes: SelectOption = {
  id: "mode",
  type: "select",
  label: "Fit",
  default: "contain",
  choices: [
    { value: "fill", label: "Fill — crop to fit" },
    { value: "contain", label: "Contain — whole image with padding" },
    { value: "stretch", label: "Stretch — distort to fit" },
    { value: "repeat", label: "Repeat — tile into the gaps" },
    { value: "blur", label: "Blur background — over a blurred copy" },
  ],
};

const fitSize: ToolOption = {
  id: "size",
  type: "number",
  label: "Size",
  default: 0,
  min: 0,
  max: 8000,
  step: 10,
  unit: "px",
  help: "0 = automatic (the image's longer side, or shorter side for Fill; at most 4096).",
};

const fitBackground = colorField(
  "background",
  "Padding colour",
  "#ffffff",
  "For Contain. A hex code, a colour name, or transparent.",
);

const colorSliders: ToolOption[] = [
  {
    id: "brightness",
    type: "number",
    label: "Brightness",
    default: 0,
    min: -100,
    max: 100,
    step: 5,
  },
  { id: "contrast", type: "number", label: "Contrast", default: 0, min: -100, max: 100, step: 5 },
  {
    id: "saturation",
    type: "number",
    label: "Saturation",
    default: 0,
    min: -100,
    max: 100,
    step: 5,
    help: "-100 is black and white.",
  },
  {
    id: "hue",
    type: "number",
    label: "Hue shift",
    default: 0,
    min: -180,
    max: 180,
    step: 5,
    unit: "°",
  },
  {
    id: "warmth",
    type: "number",
    label: "Warmth",
    default: 0,
    min: -100,
    max: 100,
    step: 5,
    help: "Negative is cooler (bluer), positive warmer.",
  },
  {
    id: "effect",
    type: "select",
    label: "Effect",
    default: "none",
    choices: [
      { value: "none", label: "None" },
      { value: "grayscale", label: "Black & white" },
      { value: "sepia", label: "Sepia" },
      { value: "vintage", label: "Vintage" },
      { value: "cool", label: "Cool" },
      { value: "warm", label: "Warm" },
      { value: "invert", label: "Invert (negative)" },
    ],
  },
];

const orderOption: SelectOption = {
  id: "order",
  type: "select",
  label: "Order",
  default: "selected",
  choices: [
    { value: "selected", label: "The order I chose them" },
    { value: "name", label: "File name (A–Z)" },
  ],
};

const pairConverter: ToolOption[] = [
  quality(90),
  colorField(
    "background",
    "Background for transparency",
    "#ffffff",
    "JPG can't be transparent: transparent areas get this colour.",
  ),
  packaging,
];

export const IMAGE_TOOL_OPTIONS: Record<string, ToolOption[]> = {
  "image-to-pdf": [
    {
      id: "size",
      type: "select",
      label: "Page size",
      default: "fit",
      choices: [
        { value: "fit", label: "Same as each image" },
        { value: "a4", label: "A4" },
        { value: "letter", label: "Letter" },
        { value: "legal", label: "Legal" },
        { value: "a3", label: "A3" },
        { value: "a5", label: "A5" },
      ],
    },
    {
      id: "orientation",
      type: "select",
      label: "Orientation",
      default: "auto",
      choices: [
        { value: "auto", label: "Match each image" },
        { value: "portrait", label: "Portrait" },
        { value: "landscape", label: "Landscape" },
      ],
      showWhen: { option: "size", equals: ["a4", "letter", "legal", "a3", "a5"] },
    },
    {
      id: "margin",
      type: "number",
      label: "Margin",
      default: 0,
      min: 0,
      max: 144,
      step: 6,
      unit: "pt",
      help: "72 pt = 1 inch.",
    },
    orderOption,
    {
      id: "output",
      type: "select",
      label: "Create",
      default: "single",
      choices: [
        { value: "single", label: "One PDF with every image" },
        { value: "separate", label: "One PDF per image" },
      ],
    },
    { ...packaging, showWhen: { option: "output", equals: ["separate"] } },
  ],
  "image-resizer": [
    {
      id: "mode",
      type: "select",
      label: "Resize by",
      default: "pixels",
      choices: [
        { value: "pixels", label: "Exact size in pixels" },
        { value: "percent", label: "Percentage" },
        { value: "longest", label: "Longest side" },
      ],
    },
    {
      id: "width",
      type: "number",
      label: "Width",
      default: 1280,
      min: 0,
      max: 20000,
      unit: "px",
      help: "0 = work it out from the height.",
      showWhen: { option: "mode", equals: ["pixels"] },
    },
    {
      id: "height",
      type: "number",
      label: "Height",
      default: 0,
      min: 0,
      max: 20000,
      unit: "px",
      help: "0 = work it out from the width.",
      showWhen: { option: "mode", equals: ["pixels"] },
    },
    {
      id: "fit",
      type: "select",
      label: "When both are set",
      default: "contain",
      choices: [
        { value: "contain", label: "Keep proportions, fit inside" },
        { value: "cover", label: "Fill exactly, crop the overflow" },
        { value: "fill", label: "Stretch to exactly that size" },
      ],
      showWhen: { option: "mode", equals: ["pixels"] },
    },
    {
      id: "percent",
      type: "number",
      label: "Scale",
      default: 50,
      min: 1,
      max: 1000,
      unit: "%",
      showWhen: { option: "mode", equals: ["percent"] },
    },
    {
      id: "longest",
      type: "number",
      label: "Longest side",
      default: 1920,
      min: 1,
      max: 20000,
      unit: "px",
      showWhen: { option: "mode", equals: ["longest"] },
    },
    { id: "noEnlarge", type: "boolean", label: "Never make an image bigger", default: false },
    packaging,
  ],
  "image-cropper": [
    {
      id: "mode",
      type: "select",
      label: "Crop by",
      default: "aspect",
      choices: [
        { value: "aspect", label: "Aspect ratio" },
        { value: "percent", label: "Trim the edges (%)" },
        { value: "box", label: "Exact box (pixels)" },
      ],
    },
    {
      id: "ratio",
      type: "text",
      label: "Aspect ratio",
      default: "1:1",
      placeholder: "16:9",
      help: "For example 1:1, 4:3, 3:2, 16:9, 9:16 or 4:5.",
      showWhen: { option: "mode", equals: ["aspect"] },
    },
    {
      id: "anchor",
      type: "select",
      label: "Keep",
      default: "smart",
      choices: [
        { value: "smart", label: "The most interesting part (automatic)" },
        { value: "center", label: "The centre" },
        { value: "top", label: "The top" },
        { value: "bottom", label: "The bottom" },
        { value: "left", label: "The left" },
        { value: "right", label: "The right" },
      ],
      showWhen: { option: "mode", equals: ["aspect"] },
    },
    ...(["left", "top", "right", "bottom"] as const).map((side): ToolOption => ({
      id: side,
      type: "number",
      label: `Trim ${side}`,
      default: 0,
      min: 0,
      max: 95,
      unit: "%",
      showWhen: { option: "mode", equals: ["percent"] },
    })),
    {
      id: "x",
      type: "number",
      label: "Left edge (x)",
      default: 0,
      min: 0,
      max: 100000,
      unit: "px",
      showWhen: { option: "mode", equals: ["box"] },
    },
    {
      id: "y",
      type: "number",
      label: "Top edge (y)",
      default: 0,
      min: 0,
      max: 100000,
      unit: "px",
      showWhen: { option: "mode", equals: ["box"] },
    },
    {
      id: "width",
      type: "number",
      label: "Width",
      default: 500,
      min: 1,
      max: 100000,
      unit: "px",
      showWhen: { option: "mode", equals: ["box"] },
    },
    {
      id: "height",
      type: "number",
      label: "Height",
      default: 500,
      min: 1,
      max: 100000,
      unit: "px",
      showWhen: { option: "mode", equals: ["box"] },
    },
    packaging,
  ],
  "image-compressor": [
    quality(75),
    {
      id: "format",
      type: "select",
      label: "Save as",
      default: "same",
      choices: [
        { value: "same", label: "Same format" },
        { value: "webp", label: "WebP (small, keeps transparency)" },
        { value: "jpg", label: "JPG" },
        { value: "avif", label: "AVIF (smallest, newer apps only)" },
        { value: "png", label: "PNG (reduced colours)" },
      ],
    },
    {
      id: "maxSide",
      type: "number",
      label: "Also shrink to at most",
      default: 0,
      min: 0,
      max: 20000,
      step: 100,
      unit: "px",
      help: "Longest side. 0 keeps the size.",
    },
    packaging,
  ],
  "image-format-converter": [
    {
      id: "format",
      type: "select",
      label: "Convert to",
      default: "png",
      choices: [
        { value: "png", label: "PNG" },
        { value: "jpg", label: "JPG" },
        { value: "webp", label: "WebP" },
        { value: "gif", label: "GIF" },
        { value: "avif", label: "AVIF" },
        { value: "tiff", label: "TIFF" },
        { value: "bmp", label: "BMP" },
      ],
    },
    quality(90, { option: "format", equals: ["jpg", "webp", "avif"] }),
    {
      ...colorField(
        "background",
        "Background for transparency",
        "#ffffff",
        "JPG and BMP can't be transparent: transparent areas get this colour.",
      ),
      showWhen: { option: "format", equals: ["jpg", "bmp"] },
    },
    packaging,
  ],
  "jpg-png-converter": pairConverter,
  "jpg-webp-converter": pairConverter,
  "png-webp-converter": [quality(90), packaging],
  "image-to-gif": [
    {
      id: "delay",
      type: "number",
      label: "Time per image",
      default: 800,
      min: 20,
      max: 10000,
      step: 20,
      unit: "ms",
      help: "Only used when there are several images.",
    },
    { id: "loop", type: "boolean", label: "Loop forever", default: true },
    {
      id: "width",
      type: "number",
      label: "Width",
      default: 0,
      min: 0,
      max: 2000,
      step: 10,
      unit: "px",
      help: "0 = the first image's width (at most 1200).",
    },
    orderOption,
    colorField(
      "background",
      "Padding colour",
      "#ffffff",
      "Fills the gaps when images have different shapes.",
    ),
  ],
  "background-blur": [
    {
      id: "mode",
      type: "select",
      label: "Keep sharp",
      default: "focus",
      choices: [
        { value: "focus", label: "A focus area (portrait style)" },
        { value: "subject", label: "The detected subject (needs a local AI model)" },
        { value: "whole", label: "Nothing — blur the whole image" },
      ],
    },
    {
      id: "strength",
      type: "number",
      label: "Blur strength",
      default: 30,
      min: 1,
      max: 100,
      step: 5,
    },
    {
      id: "focusSize",
      type: "number",
      label: "Focus area size",
      default: 60,
      min: 10,
      max: 100,
      step: 5,
      unit: "%",
      showWhen: { option: "mode", equals: ["focus"] },
    },
    {
      id: "focus",
      type: "select",
      label: "Focus area position",
      default: "center",
      choices: [
        { value: "center", label: "Centre" },
        { value: "top", label: "Top" },
        { value: "bottom", label: "Bottom" },
        { value: "left", label: "Left" },
        { value: "right", label: "Right" },
      ],
      showWhen: { option: "mode", equals: ["focus"] },
    },
  ],
  "background-removal": [
    method("plain, even backgrounds only"),
    {
      id: "tolerance",
      type: "number",
      label: "Colour tolerance",
      default: 15,
      min: 1,
      max: 60,
      help: "Built-in method: how different a pixel can be from the background colour and still be removed.",
      showWhen: { option: "method", equals: ["auto", "builtin"] },
    },
    packaging,
  ],
  "object-removal": [
    method("fills the area from its surroundings"),
    {
      id: "left",
      type: "number",
      label: "Area left edge",
      default: 40,
      min: 0,
      max: 100,
      unit: "%",
      help: "Mark the object with a box, measured in % of the image from its top-left corner.",
    },
    { id: "top", type: "number", label: "Area top edge", default: 40, min: 0, max: 100, unit: "%" },
    { id: "width", type: "number", label: "Area width", default: 20, min: 1, max: 100, unit: "%" },
    {
      id: "height",
      type: "number",
      label: "Area height",
      default: 20,
      min: 1,
      max: 100,
      unit: "%",
    },
  ],
  "image-upscaler": [
    method("sharp Lanczos resampling"),
    {
      id: "scale",
      type: "select",
      label: "Enlarge by",
      default: "2",
      choices: [
        { value: "2", label: "2×" },
        { value: "3", label: "3×" },
        { value: "4", label: "4×" },
      ],
    },
  ],
  "image-enhancer": [method("auto levels, local contrast, colour"), strength],
  "image-sharpening": [
    method("unsharp mask"),
    { id: "amount", type: "number", label: "Amount", default: 50, min: 1, max: 100, step: 5 },
  ],
  "image-denoiser": [method("median filter"), strength],
  "image-watermark": [
    {
      id: "kind",
      type: "select",
      label: "Watermark",
      default: "text",
      choices: [
        { value: "text", label: "Text" },
        { value: "logo", label: "Logo image" },
      ],
      help: "For a logo, upload it together with your images — the last file is used as the logo.",
    },
    {
      id: "text",
      type: "text",
      label: "Text",
      default: "© OneStop",
      showWhen: { option: "kind", equals: ["text"] },
    },
    {
      id: "position",
      type: "select",
      label: "Position",
      default: "bottom-right",
      choices: [...positions, { value: "tile", label: "Tiled across the image" }],
    },
    {
      id: "size",
      type: "number",
      label: "Size",
      default: 30,
      min: 2,
      max: 100,
      step: 1,
      unit: "% of width",
    },
    {
      id: "opacity",
      type: "number",
      label: "Opacity",
      default: 40,
      min: 1,
      max: 100,
      step: 5,
      unit: "%",
    },
    {
      id: "angle",
      type: "number",
      label: "Angle",
      default: 0,
      min: -180,
      max: 180,
      step: 5,
      unit: "°",
      help: "-30 gives the classic diagonal.",
    },
    {
      ...colorField("color", "Text colour", "#ffffff"),
      showWhen: { option: "kind", equals: ["text"] },
    },
    packaging,
  ],
  "add-text-to-image": [
    {
      id: "text",
      type: "text",
      label: "Text",
      default: "",
      multiline: true,
      placeholder: "Your text",
    },
    {
      id: "position",
      type: "select",
      label: "Position",
      default: "bottom-center",
      choices: [...positions, { value: "custom", label: "Exact point" }],
    },
    {
      id: "x",
      type: "number",
      label: "Across",
      default: 50,
      min: 0,
      max: 100,
      unit: "%",
      showWhen: { option: "position", equals: ["custom"] },
    },
    {
      id: "y",
      type: "number",
      label: "Down",
      default: 50,
      min: 0,
      max: 100,
      unit: "%",
      showWhen: { option: "position", equals: ["custom"] },
    },
    {
      id: "size",
      type: "number",
      label: "Text size",
      default: 8,
      min: 1,
      max: 50,
      unit: "% of height",
    },
    colorField("color", "Colour", "#ffffff"),
    {
      id: "weight",
      type: "select",
      label: "Style",
      default: "bold",
      choices: [
        { value: "regular", label: "Regular" },
        { value: "bold", label: "Bold" },
        { value: "italic", label: "Italic" },
        { value: "bold-italic", label: "Bold italic" },
      ],
    },
    {
      id: "outline",
      type: "boolean",
      label: "Outline (readable on any background)",
      default: true,
    },
    { id: "shadow", type: "boolean", label: "Drop shadow", default: false },
    {
      id: "box",
      type: "select",
      label: "Background box",
      default: "none",
      choices: [
        { value: "none", label: "None" },
        { value: "dark", label: "Dark" },
        { value: "light", label: "Light" },
      ],
    },
    {
      id: "opacity",
      type: "number",
      label: "Opacity",
      default: 100,
      min: 1,
      max: 100,
      step: 5,
      unit: "%",
    },
  ],
  "remove-image-metadata": [
    {
      id: "keepIcc",
      type: "boolean",
      label: "Keep the colour profile",
      default: true,
      help: "Colour profiles hold no personal data; removing one can shift colours.",
    },
    packaging,
  ],
  "image-color-adjustment": [...colorSliders, packaging],
  "rotate-image": [
    {
      id: "angle",
      type: "select",
      label: "Rotate by",
      default: "90",
      choices: [
        { value: "90", label: "90° clockwise" },
        { value: "180", label: "180°" },
        { value: "-90", label: "90° anticlockwise" },
        { value: "custom", label: "Any angle" },
      ],
    },
    {
      id: "customAngle",
      type: "number",
      label: "Angle",
      default: 15,
      min: -360,
      max: 360,
      unit: "°",
      help: "Positive turns clockwise.",
      showWhen: { option: "angle", equals: ["custom"] },
    },
    {
      ...colorField(
        "background",
        "Corner fill",
        "transparent",
        "Fills the corners a tilted image leaves. transparent saves as PNG if needed.",
      ),
      showWhen: { option: "angle", equals: ["custom"] },
    },
    packaging,
  ],
  "flip-image": [
    {
      id: "direction",
      type: "select",
      label: "Flip",
      default: "horizontal",
      choices: [
        { value: "horizontal", label: "Horizontally (mirror left–right)" },
        { value: "vertical", label: "Vertically (upside down)" },
        { value: "both", label: "Both" },
      ],
    },
    packaging,
  ],
  "fit-image-to-square": [
    fitModes,
    fitSize,
    { ...fitBackground, showWhen: { option: "mode", equals: ["contain"] } },
    packaging,
  ],
  "fit-image-to-circle": [
    fitModes,
    fitSize,
    { ...fitBackground, showWhen: { option: "mode", equals: ["contain"] } },
    {
      id: "border",
      type: "number",
      label: "Outline width",
      default: 0,
      min: 0,
      max: 500,
      unit: "px",
    },
    colorField(
      "borderColor",
      "Outline colour",
      "#ffffff",
      "Used when the outline width is above 0.",
    ),
    packaging,
  ],
  "meme-generator": [
    {
      id: "top",
      type: "text",
      label: "Top text",
      default: "",
      placeholder: "WHEN THE CODE COMPILES",
    },
    {
      id: "bottom",
      type: "text",
      label: "Bottom text",
      default: "",
      placeholder: "ON THE FIRST TRY",
    },
    {
      id: "size",
      type: "number",
      label: "Text size",
      default: 11,
      min: 3,
      max: 30,
      unit: "% of height",
      help: "Long captions shrink automatically.",
    },
    { id: "uppercase", type: "boolean", label: "ALL CAPS", default: true },
    colorField("color", "Text colour", "#ffffff"),
  ],
  "basic-image-editor": [
    ...(["Left", "Top", "Right", "Bottom"] as const).map((side): ToolOption => ({
      id: `trim${side}`,
      type: "number",
      label: `Crop ${side.toLowerCase()}`,
      default: 0,
      min: 0,
      max: 95,
      unit: "%",
    })),
    {
      id: "rotate",
      type: "select",
      label: "Rotate",
      default: "0",
      choices: [
        { value: "0", label: "No rotation" },
        { value: "90", label: "90° clockwise" },
        { value: "180", label: "180°" },
        { value: "270", label: "90° anticlockwise" },
      ],
    },
    {
      id: "flip",
      type: "select",
      label: "Flip",
      default: "none",
      choices: [
        { value: "none", label: "No flip" },
        { value: "horizontal", label: "Horizontally" },
        { value: "vertical", label: "Vertically" },
        { value: "both", label: "Both" },
      ],
    },
    {
      id: "maxSide",
      type: "number",
      label: "Resize longest side to",
      default: 0,
      min: 0,
      max: 10000,
      step: 10,
      unit: "px",
      help: "0 keeps the size.",
    },
    ...colorSliders,
    {
      id: "shape",
      type: "select",
      label: "Mark an area",
      default: "none",
      choices: [
        { value: "none", label: "Nothing" },
        { value: "rectangle", label: "Draw a box" },
        { value: "ellipse", label: "Draw a circle" },
        { value: "highlight", label: "Highlight" },
        { value: "blur", label: "Blur (hide a face or number)" },
        { value: "pixelate", label: "Pixelate" },
      ],
    },
    ...(
      [
        ["shapeLeft", "Area left edge", 25],
        ["shapeTop", "Area top edge", 25],
        ["shapeWidth", "Area width", 50],
        ["shapeHeight", "Area height", 50],
      ] as const
    ).map(([id, label, def]): ToolOption => ({
      id,
      type: "number",
      label,
      default: def,
      min: 0,
      max: 100,
      unit: "%",
      showWhen: {
        option: "shape",
        equals: ["rectangle", "ellipse", "highlight", "blur", "pixelate"],
      },
    })),
    {
      ...colorField("shapeColor", "Area colour", "#e53935"),
      showWhen: { option: "shape", equals: ["rectangle", "ellipse", "highlight"] },
    },
    {
      id: "captionText",
      type: "text",
      label: "Caption",
      default: "",
      placeholder: "Optional text on the image",
    },
    {
      id: "captionPosition",
      type: "select",
      label: "Caption position",
      default: "bottom-center",
      choices: positions,
    },
    {
      id: "captionSize",
      type: "number",
      label: "Caption size",
      default: 8,
      min: 1,
      max: 50,
      unit: "% of height",
    },
    colorField("captionColor", "Caption colour", "#ffffff"),
  ],
};
