// Options for the tools added in 21-roadmap-expansion.md (roadmap Part 1), except the five toolkit
// categories, which live in `options-toolkit.ts`.
//
// Same rules as every other options file: declarative only, defaults that make the tool do something
// sensible the moment its page opens, and `help` text that says what the choice actually changes.
import type { BooleanOption, NumberOption, SelectOption, TextOption, ToolOption } from "./options";

function choice(value: string, label: string) {
  return { value, label };
}

const packaging: SelectOption = {
  id: "packaging",
  type: "select",
  label: "Deliver as",
  default: "zip",
  choices: [choice("zip", "One ZIP archive"), choice("files", "Separate downloads")],
  help: "Only applies when there is more than one result.",
};

const pages: TextOption = {
  id: "pages",
  type: "text",
  label: "Pages",
  default: "",
  placeholder: "all",
  help: "Leave blank for every page. Accepts 1-3, 5, 9- and the words odd, even, first, last.",
};

const quality: SelectOption = {
  id: "quality",
  type: "select",
  label: "Quality",
  default: "good",
  choices: [choice("high", "High (largest)"), choice("good", "Good"), choice("medium", "Medium"), choice("low", "Low (smallest)")],
};

/** The AI method switch, matching the one the phase-16 tools already use. */
const aiMethod: SelectOption = {
  id: "method",
  type: "select",
  label: "Method",
  default: "auto",
  choices: [
    choice("auto", "Best available (AI when it is set up)"),
    choice("ai", "AI only"),
    choice("builtin", "Built-in only (always offline)"),
  ],
};

const aiProvider: ToolOption = { id: "aiProvider", type: "client", source: "aiProvider", label: "AI provider", default: "", visible: false };
const aiKey: ToolOption = { id: "aiKey", type: "client", source: "aiKey", label: "AI key", default: "", visible: false };
const aiCredentials: ToolOption[] = [aiProvider, aiKey];

const delimiter: SelectOption = {
  id: "delimiter",
  type: "select",
  label: "CSV separator",
  default: "auto",
  choices: [choice("auto", "Detect"), choice(",", "Comma"), choice(";", "Semicolon"), choice("\t", "Tab"), choice("|", "Pipe")],
};

const sheet: TextOption = {
  id: "sheet",
  type: "text",
  label: "Sheet",
  default: "",
  placeholder: "First sheet",
  help: "A sheet name or number. Only applies to Excel files.",
};

export const EXPANSION_TOOL_OPTIONS: Record<string, ToolOption[]> = {
  "word-counter": [
    { id: "keywords", type: "number", label: "Top keywords to list", default: 10, min: 0, max: 50, help: "The most-used words, ignoring everyday words such as “the” and “and”. Zero turns the list off." },
    { id: "saveReport", type: "boolean", label: "Also save the report as a JSON file", default: false },
  ],
  "line-sorter-and-cleaner": [
    { id: "trim", type: "boolean", label: "Trim spaces from each line", default: true },
    { id: "removeEmpty", type: "boolean", label: "Remove empty lines", default: true },
    { id: "dedupe", type: "boolean", label: "Remove duplicate lines", default: false, help: "The first copy of each line is kept." },
    { id: "ignoreCase", type: "boolean", label: "Ignore capitalisation when comparing", default: false, help: "Applies to removing duplicates and to sorting." },
    {
      id: "sort",
      type: "select",
      label: "Order",
      default: "none",
      choices: [
        choice("none", "Keep the original order"),
        choice("az", "A to Z"),
        choice("za", "Z to A"),
        choice("natural", "Natural (file2 before file10)"),
        choice("shortest", "Shortest first"),
        choice("longest", "Longest first"),
        choice("reverse", "Reverse the list"),
        choice("shuffle", "Shuffle randomly"),
      ],
    },
    { id: "prefix", type: "text", label: "Add to the start of every line", default: "", placeholder: "- " },
    { id: "suffix", type: "text", label: "Add to the end of every line", default: "", placeholder: "," },
    { id: "numberLines", type: "boolean", label: "Number the lines", default: false },
  ],
  "html-entity-converter": [
    { id: "mode", type: "select", label: "Direction", default: "encode", choices: [choice("encode", "Text → HTML entities"), choice("decode", "HTML entities → text")] },
    { id: "encodeNonAscii", type: "boolean", label: "Also encode accented and other non-ASCII characters", default: false, showWhen: { option: "mode", equals: ["encode"] }, help: "Off keeps them as they are. Turn it on for a file that must survive being saved as plain ASCII." },
  ],
  "number-base-converter": [
    {
      id: "from",
      type: "select",
      label: "The number is written in",
      default: "auto",
      choices: [choice("auto", "Detect (0x, 0b, 0o prefixes, otherwise decimal)"), choice("2", "Binary (base 2)"), choice("8", "Octal (base 8)"), choice("10", "Decimal (base 10)"), choice("16", "Hexadecimal (base 16)"), choice("36", "Base 36")],
    },
  ],
  "date-calculator": [
    { id: "mode", type: "select", label: "What do you want to know?", default: "difference", choices: [choice("difference", "How many days between two dates"), choice("add", "Add or subtract time from a date"), choice("info", "What day is this date?")] },
    { id: "start", type: "text", label: "Start date", default: "", placeholder: "2026-03-15 (blank = today)", help: "The date to count from, add to or look up. Write it as 2026-03-15, 15 March 2026 or March 15, 2026." },
    { id: "end", type: "text", label: "End date", default: "", placeholder: "2026-12-25 (blank = today)", showWhen: { option: "mode", equals: ["difference"] } },
    { id: "amount", type: "number", label: "Amount", default: 30, min: -100000, max: 100000, help: "Use a negative number to go back in time.", showWhen: { option: "mode", equals: ["add"] } },
    {
      id: "unit",
      type: "select",
      label: "Unit",
      default: "days",
      choices: [choice("days", "Days"), choice("weeks", "Weeks"), choice("months", "Months"), choice("years", "Years"), choice("business-days", "Business days (Mon–Fri)")],
      showWhen: { option: "mode", equals: ["add"] },
    },
  ],
  "percentage-calculator": [
    {
      id: "mode",
      type: "select",
      label: "What do you want to work out?",
      default: "of",
      choices: [
        choice("of", "X% of Y  (what is 15% of 240?)"),
        choice("what-percent", "X is what percent of Y?"),
        choice("change", "Percentage change from X to Y"),
        choice("increase", "Y increased by X%"),
        choice("decrease", "Y decreased by X%"),
        choice("reverse", "X is P% of what number?"),
      ],
      help: "For “X is P% of what?” put the amount in X and the percentage in Y.",
    },
    { id: "a", type: "number", label: "X", default: 15, min: -1e15, max: 1e15, step: 0.01 },
    { id: "b", type: "number", label: "Y", default: 240, min: -1e15, max: 1e15, step: 0.01 },
    { id: "decimals", type: "number", label: "Decimal places", default: 2, min: 0, max: 10 },
  ],
  "yaml-formatter-and-validator": [
    { id: "validateOnly", type: "boolean", label: "Only check that it is valid", default: false, help: "Nothing is rewritten; you just get a yes or the line and column of the first problem." },
    { id: "indent", type: "select", label: "Indentation", default: "2", choices: [choice("2", "2 spaces"), choice("4", "4 spaces")], showWhen: { option: "validateOnly", equals: ["false"] } },
    { id: "sortKeys", type: "boolean", label: "Sort keys A to Z", default: false },
  ],
  // ---- PDF (roadmap §1.1) ----------------------------------------------------------------------
  "pdf-redaction": [
    {
      id: "mode",
      type: "select",
      label: "Redact by",
      default: "text",
      choices: [choice("text", "Searching for words"), choice("regions", "Regions I give coordinates for")],
    },
    {
      id: "terms",
      type: "text",
      label: "Words or phrases to remove",
      default: "",
      multiline: true,
      placeholder: "One per line",
      showWhen: { option: "mode", equals: ["text"] },
    },
    { id: "caseSensitive", type: "boolean", label: "Match capitals exactly", default: false, showWhen: { option: "mode", equals: ["text"] } },
    {
      id: "regex",
      type: "boolean",
      label: "Treat each line as a regular expression",
      default: false,
      showWhen: { option: "mode", equals: ["text"] },
      help: "For patterns like \\d{3}-\\d{2}-\\d{4}.",
    },
    { id: "padding", type: "number", label: "Padding round each match", default: 1.5, min: 0, max: 12, step: 0.5, unit: "pt", showWhen: { option: "mode", equals: ["text"] } },
    {
      id: "regions",
      type: "text",
      label: "Regions",
      default: "",
      multiline: true,
      placeholder: "1: 50,600,200,20",
      help: "One per line: page: x,y,width,height in points, measured from the bottom-left.",
      showWhen: { option: "mode", equals: ["regions"] },
    },
    { id: "color", type: "select", label: "Fill", default: "black", choices: [choice("black", "Black"), choice("white", "White")] },
    {
      id: "dpi",
      type: "number",
      label: "Re-render pages at",
      default: 150,
      min: 72,
      max: 300,
      step: 6,
      unit: "DPI",
      help: "Redacted pages become images so the text is truly gone. Higher is sharper and larger.",
    },
  ],
  "pdf-bookmark-editor": [
    {
      id: "mode",
      type: "select",
      label: "What to do",
      default: "read",
      choices: [
        choice("read", "Show the bookmarks it already has"),
        choice("replace", "Replace them with my list"),
        choice("from-headings", "Build them from the document's headings"),
        choice("clear", "Remove all bookmarks"),
      ],
    },
    {
      id: "bookmarks",
      type: "text",
      label: "Bookmarks",
      default: "",
      multiline: true,
      placeholder: "Introduction | 1\n  Background | 2\nMethod | 7",
      help: "One per line: title | page. Indent by two spaces to nest one under another.",
      showWhen: { option: "mode", equals: ["replace"] },
    },
    { id: "showPanel", type: "boolean", label: "Open the bookmark panel by default", default: true },
  ],
  "pdf-chapter-splitter": [
    {
      id: "depth",
      type: "number",
      label: "Split on bookmarks down to level",
      default: 1,
      min: 1,
      max: 4,
      help: "1 splits on top-level chapters only; 2 also splits on their sub-sections.",
    },
    packaging,
  ],
  "pdf-booklet-layout": [
    {
      id: "style",
      type: "select",
      label: "Layout",
      default: "saddle-stitch",
      choices: [
        choice("saddle-stitch", "Saddle stitch (fold and staple)"),
        choice("sequential-2up", "Two-up in reading order"),
      ],
      help: "Saddle stitch reorders the pages so a folded stack reads correctly.",
    },
    { id: "gutter", type: "number", label: "Gutter between pages", default: 0, min: 0, max: 72, unit: "pt" },
    { id: "margin", type: "number", label: "Outer margin", default: 0, min: 0, max: 72, unit: "pt" },
  ],
  "pdf-table-extractor": [
    pages,
    { id: "format", type: "select", label: "Save as", default: "csv", choices: [choice("csv", "CSV"), choice("json", "JSON"), choice("both", "Both")] },
    { id: "separateFiles", type: "boolean", label: "One CSV per page", default: true, showWhen: { option: "format", equals: ["csv", "both"] } },
    { id: "firstRowIsHeader", type: "boolean", label: "Treat the first row as headings", default: true, showWhen: { option: "format", equals: ["json", "both"] } },
    { id: "minRows", type: "number", label: "Ignore tables with fewer than", default: 2, min: 1, max: 100, unit: "rows" },
    { id: "minColumns", type: "number", label: "Ignore tables with fewer than", default: 2, min: 1, max: 50, unit: "columns" },
  ],
  "pdf-accessibility-checker": [],
  "pdf-visual-diff": [
    pages,
    { id: "dpi", type: "number", label: "Compare at", default: 110, min: 72, max: 200, step: 2, unit: "DPI" },
    {
      id: "threshold",
      type: "number",
      label: "Ignore differences smaller than",
      default: 12,
      min: 0,
      max: 255,
      help: "Higher ignores anti-aliasing and compression noise; lower catches every pixel.",
    },
    { id: "includeUnchanged", type: "boolean", label: "Include pages that did not change", default: false },
  ],
  "pdf-form-designer": [
    {
      id: "fields",
      type: "text",
      label: "Fields",
      default: "text | Full name | 1 | 60,700,220,22\ntext | Email | 1 | 60,660,220,22\ncheckbox | I agree | 1 | 60,620,16,16",
      multiline: true,
      help: "One per line: kind | label | page | x,y,width,height. Kinds: text, multiline, checkbox, dropdown, radio. Dropdown and radio take a fifth part with comma-separated choices.",
    },
    { id: "drawLabels", type: "boolean", label: "Print each label above its field", default: true },
    { id: "border", type: "boolean", label: "Draw a border round each field", default: true },
  ],

  // ---- Word / PowerPoint (roadmap §1.2) --------------------------------------------------------
  "track-changes-cleaner": [
    {
      id: "mode",
      type: "select",
      label: "Tracked changes",
      default: "accept",
      choices: [choice("accept", "Accept all"), choice("reject", "Reject all")],
    },
    { id: "comments", type: "boolean", label: "Remove comments too", default: true },
    { id: "formatting", type: "boolean", label: "Clear formatting revisions", default: true },
  ],
  "markdown-to-word": [{ id: "title", type: "text", label: "Document title", default: "", placeholder: "From the file name" }],
  "word-to-markdown": [],
  "citation-formatter": [
    {
      id: "style",
      type: "select",
      label: "Style",
      default: "apa",
      choices: [
        choice("apa", "APA 7"),
        choice("mla", "MLA 9"),
        choice("chicago", "Chicago"),
        choice("harvard", "Harvard"),
        choice("ieee", "IEEE"),
        choice("bibtex", "BibTeX"),
      ],
    },
    { id: "sort", type: "boolean", label: "Sort alphabetically", default: true },
  ],
  "resume-template-filler": [
    { id: "format", type: "select", label: "Download as", default: "docx", choices: [choice("docx", "Word"), choice("pdf", "PDF"), choice("both", "Both")] },
  ],
  "markdown-to-slides": [
    {
      id: "splitLevel",
      type: "number",
      label: "Start a new slide at heading level",
      default: 2,
      min: 1,
      max: 4,
      help: "Ignored when the file already separates slides with a line of ---.",
    },
    {
      id: "theme",
      type: "select",
      label: "Theme",
      default: "chrome",
      choices: [choice("chrome", "Light (polished chrome)"), choice("lacquer", "Dark (black lacquer)"), choice("paper", "Paper")],
    },
    { id: "widescreen", type: "boolean", label: "16:9 widescreen", default: true },
    { id: "title", type: "text", label: "Deck title", default: "", placeholder: "From the file name" },
  ],

  // ---- Data (roadmap §1.3) ---------------------------------------------------------------------
  "pivot-table-builder": [
    { id: "rows", type: "text", label: "Group rows by", default: "", placeholder: "Column name, letter or number" },
    { id: "columns", type: "text", label: "Group columns by", default: "", placeholder: "Leave blank for a single column" },
    { id: "values", type: "text", label: "Values from", default: "", placeholder: "Column to aggregate" },
    {
      id: "aggregate",
      type: "select",
      label: "Aggregate with",
      default: "sum",
      choices: [
        choice("sum", "Sum"),
        choice("count", "Count"),
        choice("average", "Average"),
        choice("median", "Median"),
        choice("min", "Minimum"),
        choice("max", "Maximum"),
        choice("distinct", "Distinct values"),
        choice("first", "First value"),
      ],
    },
    { id: "totals", type: "boolean", label: "Add totals", default: true },
    { id: "sortBy", type: "select", label: "Order rows by", default: "label", choices: [choice("label", "Group name"), choice("value", "Total, largest first")] },
    { id: "output", type: "select", label: "Save as", default: "csv", choices: [choice("csv", "CSV"), choice("xlsx", "Excel")] },
    { id: "maxRows", type: "number", label: "Refuse more than", default: 5000, min: 10, max: 100000, unit: "rows" },
    sheet,
    delimiter,
  ],
  "chart-generator": [
    {
      id: "type",
      type: "select",
      label: "Chart type",
      default: "column",
      choices: [
        choice("column", "Columns (vertical bars)"),
        choice("bar", "Bars (horizontal)"),
        choice("line", "Line"),
        choice("area", "Area"),
        choice("pie", "Pie"),
        choice("doughnut", "Doughnut"),
        choice("scatter", "Scatter"),
      ],
    },
    { id: "labels", type: "text", label: "Labels from", default: "", placeholder: "First column" },
    { id: "values", type: "text", label: "Values from", default: "", placeholder: "Second column" },
    { id: "title", type: "text", label: "Title", default: "", placeholder: "From the column names" },
    { id: "width", type: "number", label: "Width", default: 900, min: 240, max: 3000, step: 20, unit: "px" },
    { id: "height", type: "number", label: "Height", default: 520, min: 180, max: 3000, step: 20, unit: "px" },
    { id: "showValues", type: "boolean", label: "Print the value on each point", default: true },
    { id: "dark", type: "boolean", label: "Dark background", default: false },
    { id: "format", type: "select", label: "Save as", default: "svg", choices: [choice("svg", "SVG (sharp at any size)"), choice("png", "PNG"), choice("both", "Both")] },
    { id: "maxPoints", type: "number", label: "Plot at most", default: 60, min: 2, max: 500, unit: "points" },
    sheet,
    delimiter,
  ],
  "data-diff": [
    {
      id: "key",
      type: "text",
      label: "Match rows on",
      default: "",
      placeholder: "Leave blank to compare in order",
      help: "A column that identifies a row (an id, an email). With one, a row that moved is not reported as a change.",
    },
    { id: "trimWhitespace", type: "boolean", label: "Ignore leading and trailing spaces", default: true },
    { id: "ignoreCase", type: "boolean", label: "Ignore capitalisation", default: false },
    sheet,
    delimiter,
  ],
  "json-schema-generator": [
    { id: "title", type: "text", label: "Schema title", default: "", placeholder: "From the file name" },
    {
      id: "treatArrayAsSamples",
      type: "boolean",
      label: "Treat a top-level array as many samples",
      default: true,
      help: "On: the schema describes one item. Off: it describes the array itself.",
    },
    { id: "wrapArray", type: "boolean", label: "Wrap the result as an array schema", default: false, showWhen: { option: "treatArrayAsSamples", equals: ["true"] } },
    { id: "enums", type: "boolean", label: "Infer enums from small repeated value sets", default: true },
    { id: "examples", type: "boolean", label: "Include examples", default: true },
    { id: "draft", type: "select", label: "Draft", default: "2020-12", choices: [choice("2020-12", "2020-12 (current)"), choice("07", "Draft 07")] },
  ],
  "sample-data-generator": [
    {
      id: "fields",
      type: "text",
      label: "Columns",
      default: "id:id, name:fullName, email:email, joined:date, active:boolean",
      multiline: true,
      help: "name:type per column. Types: id, uuid, firstName, lastName, fullName, email, username, phone, company, jobTitle, street, city, country, postcode, date, datetime, boolean, integer, decimal, price, percent, status, product, sentence, paragraph, url, ipv4, colorHex.",
    },
    { id: "rows", type: "number", label: "Rows", default: 25, min: 1, max: 20000 },
    { id: "format", type: "select", label: "Save as", default: "csv", choices: [choice("csv", "CSV"), choice("json", "JSON"), choice("both", "Both")] },
  ],

  // ---- Images (roadmap §1.4) -------------------------------------------------------------------
  "color-palette-extractor": [
    { id: "colors", type: "number", label: "Colours", default: 6, min: 2, max: 24 },
    { id: "ignoreTransparent", type: "boolean", label: "Ignore transparent pixels", default: true },
    { id: "pngStrip", type: "boolean", label: "Also save the swatches as a PNG", default: false },
  ],
  "image-to-ascii-art": [
    { id: "columns", type: "number", label: "Width", default: 100, min: 16, max: 400, unit: "characters" },
    {
      id: "ramp",
      type: "select",
      label: "Character set",
      default: "standard",
      choices: [
        choice("standard", "Standard (@%#*+=-:. )"),
        choice("blocks", "Block shading (█▓▒░)"),
        choice("detailed", "Detailed (70 characters)"),
        choice("minimal", "Minimal (#+-. )"),
      ],
    },
    { id: "invert", type: "boolean", label: "Invert (for light-on-dark)", default: false },
    { id: "html", type: "boolean", label: "Also save a ready-to-view HTML page", default: false },
  ],
  "favicon-set-generator": [
    { id: "appName", type: "text", label: "App name", default: "", placeholder: "From the file name" },
    { id: "themeColor", type: "text", label: "Theme colour", default: "#111417", placeholder: "#111417" },
    { id: "transparent", type: "boolean", label: "Keep transparency", default: true },
    { id: "background", type: "text", label: "Background", default: "#ffffff", showWhen: { option: "transparent", equals: ["false"] } },
    { id: "rounded", type: "boolean", label: "Round the corners", default: false },
  ],
  "social-media-preset-resizer": [
    {
      id: "presets",
      type: "text",
      label: "Presets",
      default: "",
      multiline: true,
      placeholder: "Blank for a sensible spread",
      help: "Space-separated ids: instagram-square, instagram-portrait, instagram-story, youtube-thumbnail, youtube-banner, open-graph, twitter-card, linkedin-banner, linkedin-post, facebook-cover, tiktok, pinterest, podcast-cover, email-header.",
    },
    {
      id: "fit",
      type: "select",
      label: "Fit",
      default: "cover",
      choices: [choice("cover", "Fill the frame (crops)"), choice("contain", "Fit inside (adds background)")],
    },
    {
      id: "position",
      type: "select",
      label: "Crop towards",
      default: "attention",
      choices: [
        choice("attention", "The most interesting part"),
        choice("entropy", "The busiest part"),
        choice("centre", "The centre"),
        choice("top", "The top"),
        choice("bottom", "The bottom"),
        choice("left", "The left"),
        choice("right", "The right"),
      ],
      showWhen: { option: "fit", equals: ["cover"] },
    },
    { id: "background", type: "text", label: "Background", default: "#ffffff", showWhen: { option: "fit", equals: ["contain"] } },
    { id: "format", type: "select", label: "Save as", default: "jpg", choices: [choice("jpg", "JPG"), choice("png", "PNG"), choice("webp", "WebP"), choice("same", "Same as the original")] },
    { id: "quality", type: "number", label: "Quality", default: 88, min: 40, max: 100, unit: "%" },
    packaging,
  ],
  "collage-maker": [
    { id: "columns", type: "number", label: "Columns", default: 0, min: 0, max: 20, help: "0 chooses a square-ish grid for however many images you gave." },
    { id: "cellSize", type: "number", label: "Each cell", default: 400, min: 40, max: 2000, step: 20, unit: "px" },
    { id: "gap", type: "number", label: "Gap", default: 8, min: 0, max: 200, unit: "px" },
    { id: "padding", type: "number", label: "Outer padding", default: 16, min: 0, max: 400, unit: "px" },
    { id: "fit", type: "select", label: "Fit", default: "cover", choices: [choice("cover", "Fill each cell (crops)"), choice("contain", "Fit inside each cell")] },
    { id: "labels", type: "boolean", label: "Print each file name underneath", default: false },
    { id: "background", type: "text", label: "Background", default: "#ffffff" },
    { id: "format", type: "select", label: "Save as", default: "jpg", choices: [choice("jpg", "JPG"), choice("png", "PNG"), choice("webp", "WebP")] },
    { id: "quality", type: "number", label: "Quality", default: 90, min: 40, max: 100, unit: "%" },
  ],
  "batch-image-renamer": [
    {
      id: "pattern",
      type: "text",
      label: "Pattern",
      default: "{name}-{n}",
      help: "{name} the original name · {n} a number (use {n:3} to pad it) · {date} · {time} · {ext}.",
    },
    { id: "start", type: "number", label: "Start numbering at", default: 1, min: 0, max: 100000 },
    { id: "step", type: "number", label: "Step", default: 1, min: 1, max: 1000 },
    {
      id: "sort",
      type: "select",
      label: "Number them in",
      default: "given",
      choices: [choice("given", "The order I chose them"), choice("name", "Name order"), choice("size", "Size order, largest first")],
    },
    { id: "case", type: "select", label: "Letter case", default: "keep", choices: [choice("keep", "Leave as is"), choice("lower", "lower case"), choice("upper", "UPPER CASE")] },
  ],
  "sprite-sheet-generator": [
    { id: "mode", type: "select", label: "What to do", default: "pack", choices: [choice("pack", "Pack images into a sheet"), choice("slice", "Slice a sheet into images")] },
    { id: "padding", type: "number", label: "Padding between sprites", default: 2, min: 0, max: 64, unit: "px", showWhen: { option: "mode", equals: ["pack"] } },
    { id: "maxWidth", type: "number", label: "Sheet width limit", default: 2048, min: 64, max: 8192, step: 64, unit: "px", showWhen: { option: "mode", equals: ["pack"] } },
    { id: "tileSize", type: "number", label: "Resize each sprite to fit", default: 0, min: 0, max: 1024, unit: "px", help: "0 keeps every sprite at its own size.", showWhen: { option: "mode", equals: ["pack"] } },
    { id: "transparent", type: "boolean", label: "Transparent background", default: true, showWhen: { option: "mode", equals: ["pack"] } },
    { id: "background", type: "text", label: "Background", default: "#000000", showWhen: { option: "transparent", equals: ["false"] } },
    { id: "sliceColumns", type: "number", label: "Columns", default: 4, min: 1, max: 64, showWhen: { option: "mode", equals: ["slice"] } },
    { id: "sliceRows", type: "number", label: "Rows", default: 4, min: 1, max: 64, showWhen: { option: "mode", equals: ["slice"] } },
  ],
  "near-duplicate-image-finder": [
    {
      id: "threshold",
      type: "number",
      label: "Similarity threshold",
      default: 8,
      min: 0,
      max: 32,
      help: "Hamming distance between perceptual hashes. 0 is visually identical; 8 catches resizes and recompressions; above 16 starts grouping merely similar pictures.",
    },
  ],
  "color-blindness-simulator": [
    {
      id: "kind",
      type: "select",
      label: "Simulate",
      default: "deuteranopia",
      choices: [
        choice("deuteranopia", "Deuteranopia (no green cones — most common)"),
        choice("protanopia", "Protanopia (no red cones)"),
        choice("tritanopia", "Tritanopia (no blue cones)"),
        choice("achromatopsia", "Achromatopsia (no colour at all)"),
        choice("all", "All four"),
      ],
    },
    { id: "severity", type: "number", label: "Severity", default: 100, min: 10, max: 100, step: 5, unit: "%" },
    packaging,
  ],
  "image-vectorizer": [
    { id: "detail", type: "number", label: "Detail", default: 50, min: 5, max: 100, help: "Higher follows the outline more closely and makes a bigger file." },
    { id: "threshold", type: "number", label: "Light/dark cut-off", default: 50, min: 1, max: 99, unit: "%" },
    { id: "invert", type: "boolean", label: "Trace the light areas instead", default: false },
    { id: "minArea", type: "number", label: "Ignore shapes smaller than", default: 12, min: 0, max: 5000, unit: "px²" },
    { id: "fill", type: "text", label: "Fill colour", default: "#111417" },
    { id: "transparent", type: "boolean", label: "Transparent background", default: true },
    { id: "background", type: "text", label: "Background", default: "#ffffff", showWhen: { option: "transparent", equals: ["false"] } },
  ],
  "photo-map-viewer": [],

  // ---- Audio / video (roadmap §1.5) ------------------------------------------------------------
  "silence-trimmer": [
    { id: "mode", type: "select", label: "Remove silence", default: "all", choices: [choice("all", "Everywhere"), choice("edges", "Only at the start and end")] },
    {
      id: "thresholdDb",
      type: "number",
      label: "Count as silence below",
      default: -35,
      min: -70,
      max: -10,
      unit: "dB",
      help: "A quiet room floor is about -50 dB; a noisy recording may need -25.",
    },
    { id: "minSilence", type: "number", label: "Only gaps longer than", default: 0.6, min: 0.1, max: 10, step: 0.1, unit: "seconds" },
    { id: "keep", type: "number", label: "Leave behind", default: 0.2, min: 0, max: 5, step: 0.05, unit: "seconds", help: "A little silence kept in each gap, so speech does not run together." },
    packaging,
  ],
  "podcast-chapter-marker": [
    {
      id: "chapters",
      type: "text",
      label: "Chapters",
      default: "",
      multiline: true,
      placeholder: "00:00 Introduction\n04:12 The interview\n38:40 Closing thoughts",
      help: "A timestamp then a title, one per line.",
    },
    { id: "title", type: "text", label: "Title", default: "", placeholder: "Leave blank to keep the current one" },
    { id: "artist", type: "text", label: "Artist / host", default: "" },
    { id: "album", type: "text", label: "Show / album", default: "" },
    packaging,
  ],
  "waveform-video-generator": [
    {
      id: "style",
      type: "select",
      label: "Style",
      default: "bars",
      choices: [choice("bars", "Bars"), choice("line", "Line"), choice("cline", "Centred line"), choice("point", "Points"), choice("spectrum", "Spectrogram")],
    },
    { id: "width", type: "number", label: "Width", default: 1280, min: 320, max: 3840, step: 16, unit: "px" },
    { id: "height", type: "number", label: "Height", default: 720, min: 180, max: 2160, step: 16, unit: "px" },
    { id: "fps", type: "number", label: "Frame rate", default: 25, min: 10, max: 60, unit: "fps" },
    { id: "color", type: "text", label: "Waveform colour", default: "#8fa2b4" },
    { id: "background", type: "text", label: "Background", default: "#111417" },
    packaging,
  ],
  "text-to-speech-reader": [
    { id: "speed", type: "number", label: "Speed", default: 100, min: 50, max: 200, step: 5, unit: "%" },
    { id: "format", type: "select", label: "Save as", default: "mp3", choices: [choice("mp3", "MP3"), choice("wav", "WAV (uncompressed)")] },
    { id: "bitrate", type: "number", label: "Bitrate", default: 128, min: 64, max: 320, step: 32, unit: "kbps", showWhen: { option: "format", equals: ["mp3"] } },
    { id: "maxCharacters", type: "number", label: "Refuse more than", default: 20000, min: 100, max: 200000, unit: "characters" },
  ],
  "auto-subtitle-generator": [
    {
      id: "language",
      type: "select",
      label: "Spoken language",
      default: "auto",
      choices: [
        choice("auto", "Detect"),
        choice("en", "English"),
        choice("es", "Spanish"),
        choice("fr", "French"),
        choice("de", "German"),
        choice("it", "Italian"),
        choice("pt", "Portuguese"),
        choice("nl", "Dutch"),
        choice("pl", "Polish"),
        choice("ru", "Russian"),
        choice("tr", "Turkish"),
        choice("uk", "Ukrainian"),
        choice("hi", "Hindi"),
        choice("ar", "Arabic"),
        choice("zh", "Chinese"),
        choice("ja", "Japanese"),
        choice("ko", "Korean"),
      ],
    },
    { id: "translate", type: "boolean", label: "Translate into English", default: false },
    { id: "format", type: "select", label: "Save as", default: "srt", choices: [choice("srt", "SubRip (.srt)"), choice("vtt", "WebVTT (.vtt)"), choice("txt", "Plain transcript")] },
    { id: "maxLineLength", type: "number", label: "Wrap captions at", default: 42, min: 20, max: 120, unit: "characters" },
    { id: "threads", type: "number", label: "CPU threads", default: 0, min: 0, max: 32, help: "0 lets whisper.cpp decide." },
    packaging,
  ],
  "video-stabilizer": [
    { id: "shakiness", type: "number", label: "How shaky it is", default: 5, min: 1, max: 10 },
    { id: "smoothing", type: "number", label: "Smooth over", default: 15, min: 1, max: 100, unit: "frames" },
    { id: "zoom", type: "number", label: "Zoom", default: 0, min: -20, max: 20, unit: "%", help: "A little zoom hides the edges the correction moves out of frame." },
    { id: "crop", type: "select", label: "Edges", default: "black", choices: [choice("black", "Fill with black"), choice("keep", "Keep the previous frame's pixels")] },
    quality,
    packaging,
  ],
  "video-contact-sheet": [
    { id: "columns", type: "number", label: "Columns", default: 4, min: 1, max: 12 },
    { id: "rows", type: "number", label: "Rows", default: 4, min: 1, max: 12 },
    { id: "tileWidth", type: "number", label: "Each frame", default: 320, min: 80, max: 960, step: 20, unit: "px wide" },
    { id: "timestamps", type: "boolean", label: "Stamp each frame with its time", default: true },
    { id: "format", type: "select", label: "Save as", default: "jpg", choices: [choice("jpg", "JPG"), choice("png", "PNG")] },
    packaging,
  ],
  "subtitle-burner": [
    { id: "fontSize", type: "number", label: "Font size", default: 24, min: 10, max: 96, unit: "px" },
    { id: "color", type: "text", label: "Text colour", default: "#ffffff" },
    { id: "outlineColor", type: "text", label: "Outline colour", default: "#000000" },
    { id: "outlineWidth", type: "number", label: "Outline", default: 2, min: 0, max: 6, unit: "px" },
    { id: "box", type: "boolean", label: "Put the text in a solid box", default: false },
    { id: "bold", type: "boolean", label: "Bold", default: false },
    { id: "marginBottom", type: "number", label: "Distance from the bottom", default: 28, min: 0, max: 400, unit: "px" },
    quality,
  ],

  // ---- QR / barcodes (roadmap §1.6) ------------------------------------------------------------
  "barcode-generator": [
    {
      id: "symbology",
      type: "select",
      label: "Barcode type",
      default: "code128",
      choices: [
        choice("code128", "Code 128 (any text)"),
        choice("ean13", "EAN-13 (retail, 13 digits)"),
        choice("ean8", "EAN-8 (small retail, 8 digits)"),
        choice("upca", "UPC-A (North American retail, 12 digits)"),
        choice("code39", "Code 39 (older industrial)"),
        choice("itf14", "ITF-14 (shipping cartons, 14 digits)"),
      ],
    },
    { id: "height", type: "number", label: "Bar height", default: 120, min: 20, max: 600, unit: "px" },
    { id: "moduleWidth", type: "number", label: "Narrowest bar", default: 2, min: 1, max: 12, unit: "px" },
    { id: "quietZone", type: "number", label: "Quiet zone", default: 10, min: 0, max: 40, unit: "modules", help: "Blank space either side. Scanners need it; 10 is the usual minimum." },
    { id: "showText", type: "boolean", label: "Print the number underneath", default: true },
    { id: "dark", type: "text", label: "Bar colour", default: "#000000" },
    { id: "light", type: "text", label: "Background", default: "#ffffff" },
    { id: "format", type: "select", label: "Save as", default: "svg", choices: [choice("svg", "SVG (sharp at any size)"), choice("png", "PNG")] },
  ],
  "batch-qr-generator": [
    { id: "column", type: "text", label: "CSV column", default: "", placeholder: "First column" },
    { id: "header", type: "boolean", label: "The first row is headings", default: true },
    { id: "prefix", type: "text", label: "Put this in front of every value", default: "", placeholder: "https://example.com/" },
    { id: "format", type: "select", label: "Save each as", default: "png", choices: [choice("png", "PNG"), choice("svg", "SVG")] },
    { id: "size", type: "number", label: "Size", default: 512, min: 128, max: 2048, step: 32, unit: "px" },
    { id: "printSheet", type: "boolean", label: "Include an A4 print sheet", default: true },
    { id: "limit", type: "number", label: "Refuse more than", default: 500, min: 1, max: 2000, unit: "codes" },
  ],
  "logo-qr-code": [
    { id: "logo", type: "image", label: "Logo", default: "" },
    {
      id: "logoScale",
      type: "number",
      label: "Logo width",
      default: 22,
      min: 8,
      max: 35,
      unit: "% of the code",
      help: "OneStop decodes the finished image to check it still scans, and shrinks the logo until it does.",
    },
    { id: "size", type: "number", label: "Size", default: 720, min: 256, max: 2048, step: 32, unit: "px" },
    { id: "dark", type: "text", label: "Module colour", default: "#000000" },
    { id: "light", type: "text", label: "Background", default: "#ffffff" },
  ],

  // ---- AI (roadmap §1.7) -----------------------------------------------------------------------
  "ai-flashcard-generator": [
    { id: "count", type: "number", label: "Cards", default: 12, min: 1, max: 60 },
    {
      id: "format",
      type: "select",
      label: "Card style",
      default: "qa",
      choices: [
        choice("qa", "Question and answer"),
        choice("multiple-choice", "Multiple choice"),
        choice("cloze", "Fill in the blank (works with no AI at all)"),
      ],
    },
    {
      id: "difficulty",
      type: "select",
      label: "Aim at",
      default: "mixed",
      choices: [choice("mixed", "A mix"), choice("recall", "Factual recall"), choice("understanding", "Understanding and application")],
    },
    aiMethod,
    ...aiCredentials,
  ],
  "ai-code-explainer": [
    {
      id: "mode",
      type: "select",
      label: "What to do",
      default: "explain",
      choices: [
        choice("explain", "Explain what it does"),
        choice("review", "Review it for problems"),
        choice("comment", "Add comments"),
        choice("tests", "Suggest test cases"),
        choice("simplify", "Suggest simplifications"),
      ],
    },
    {
      id: "audience",
      type: "select",
      label: "Written for",
      default: "developer",
      choices: [choice("new", "Someone new to programming"), choice("developer", "A working developer"), choice("expert", "An expert")],
    },
    { id: "language", type: "text", label: "Language", default: "", placeholder: "Detected from the file" },
    ...aiCredentials,
  ],
  "ai-resume-matcher": [
    { id: "jobDescription", type: "text", label: "Job description", default: "", multiline: true, placeholder: "Paste the whole posting" },
    aiMethod,
    ...aiCredentials,
  ],
  "ai-alt-text-generator": [
    {
      id: "purpose",
      type: "select",
      label: "What the image is for",
      default: "informative",
      choices: [
        choice("informative", "It carries information"),
        choice("complex", "It is a chart, diagram or map"),
        choice("functional", "It is a button, icon or link"),
        choice("decorative", "It is purely decorative"),
      ],
      help: "Decorative images should have empty alt text so screen readers skip them — this tool will say so rather than describing them.",
    },
    { id: "maxLength", type: "number", label: "Keep it under", default: 125, min: 40, max: 400, unit: "characters" },
    ...aiCredentials,
  ],
  "ai-meeting-summarizer": [
    {
      id: "style",
      type: "select",
      label: "Write",
      default: "minutes",
      choices: [
        choice("minutes", "Minutes (summary, decisions, actions)"),
        choice("brief", "A short brief"),
        choice("study-notes", "Study notes"),
        choice("decisions", "Only the decisions and actions"),
      ],
    },
    { id: "language", type: "text", label: "Spoken language", default: "", placeholder: "Detected" },
    { id: "includeTranscript", type: "boolean", label: "Also save the full transcript", default: true },
    aiMethod,
    ...aiCredentials,
  ],

  // ---- Developer / utility (roadmap §1.8) ------------------------------------------------------
  "jwt-decoder": [
    {
      id: "secret",
      type: "text",
      label: "Secret (optional)",
      default: "",
      secret: true,
      help: "For HS256/384/512 tokens only, to verify the signature. RS/ES tokens are decoded but not verified — checking those would mean fetching a key over the internet.",
    },
  ],
  "color-converter": [
    {
      id: "palette",
      type: "select",
      label: "Also generate",
      default: "shades",
      choices: [
        choice("shades", "A shade ramp"),
        choice("monochromatic", "Monochromatic variants"),
        choice("complementary", "The complement"),
        choice("analogous", "Analogous colours"),
        choice("triadic", "A triad"),
        choice("tetradic", "A tetrad"),
        choice("none", "Nothing"),
      ],
    },
    { id: "steps", type: "number", label: "Steps", default: 7, min: 2, max: 16, showWhen: { option: "palette", equals: ["shades", "monochromatic"] } },
    { id: "against", type: "text", label: "Check contrast against", default: "", placeholder: "#ffffff, or a colour name" },
  ],
  "cron-expression-builder": [
    { id: "expression", type: "text", label: "Expression", default: "30 6 * * 1-5", placeholder: "30 6 * * 1-5" },
    { id: "runs", type: "number", label: "Show the next", default: 5, min: 1, max: 50, unit: "runs" },
  ],
  "text-diff-viewer": [
    { id: "against", type: "text", label: "Compare with", default: "", multiline: true, placeholder: "The other version (not needed if you chose two files)" },
    { id: "granularity", type: "select", label: "Highlight", default: "line", choices: [choice("line", "Whole changed lines"), choice("word", "The changed words within a line")] },
    { id: "ignoreWhitespace", type: "boolean", label: "Ignore leading and trailing spaces", default: false },
    { id: "ignoreCase", type: "boolean", label: "Ignore capitalisation", default: false },
    { id: "ignoreBlankLines", type: "boolean", label: "Ignore blank lines", default: false },
  ],
  "case-converter": [
    {
      id: "style",
      type: "select",
      label: "Convert to",
      default: "camel",
      choices: [
        choice("camel", "camelCase"),
        choice("pascal", "PascalCase"),
        choice("snake", "snake_case"),
        choice("kebab", "kebab-case"),
        choice("constant", "CONSTANT_CASE"),
        choice("dot", "dot.case"),
        choice("path", "path/case"),
        choice("train", "Train-Case"),
        choice("title", "Title Case"),
        choice("sentence", "Sentence case"),
        choice("lower", "lower case"),
        choice("upper", "UPPER CASE"),
        choice("alternating", "aLtErNaTiNg"),
        choice("inverse", "iNVERSE"),
      ],
    },
    { id: "perLine", type: "boolean", label: "Convert each line separately", default: true },
  ],
  "unit-converter": [
    {
      id: "family",
      type: "select",
      label: "Measuring",
      default: "length",
      choices: [
        choice("length", "Length"),
        choice("mass", "Weight"),
        choice("temperature", "Temperature"),
        choice("area", "Area"),
        choice("volume", "Volume"),
        choice("speed", "Speed"),
        choice("data", "Data size"),
        choice("time", "Time"),
        choice("pressure", "Pressure"),
        choice("energy", "Energy"),
        choice("angle", "Angle"),
      ],
    },
    { id: "value", type: "number", label: "Value", default: 1, min: -1000000000000000, max: 1000000000000000 },
    { id: "from", type: "text", label: "From", default: "km" },
    { id: "to", type: "text", label: "To", default: "mi", help: 'You can also type the whole thing in the box above, like "12 km to mi".' },
  ],
  "lorem-ipsum-generator": [
    {
      id: "kind",
      type: "select",
      label: "Generate",
      default: "paragraphs",
      choices: [
        choice("paragraphs", "Paragraphs"),
        choice("sentences", "Sentences"),
        choice("words", "Words"),
        choice("json", "Placeholder JSON records"),
        choice("image", "A placeholder image"),
      ],
    },
    { id: "count", type: "number", label: "How many", default: 3, min: 1, max: 500 },
    { id: "classicOpening", type: "boolean", label: 'Start with "Lorem ipsum dolor sit amet"', default: true, showWhen: { option: "kind", equals: ["paragraphs", "sentences"] } },
    { id: "html", type: "boolean", label: "Wrap paragraphs in <p> tags", default: false, showWhen: { option: "kind", equals: ["paragraphs"] } },
    { id: "width", type: "number", label: "Width", default: 640, min: 16, max: 4000, unit: "px", showWhen: { option: "kind", equals: ["image"] } },
    { id: "height", type: "number", label: "Height", default: 360, min: 16, max: 4000, unit: "px", showWhen: { option: "kind", equals: ["image"] } },
    { id: "label", type: "text", label: "Label", default: "", placeholder: "The dimensions", showWhen: { option: "kind", equals: ["image"] } },
  ],
  "api-request-tester": [
    {
      id: "method",
      type: "select",
      label: "Method",
      default: "GET",
      choices: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"].map((m) => choice(m, m)),
    },
    { id: "headers", type: "text", label: "Headers", default: "", multiline: true, placeholder: "Accept: application/json\nX-Request-Id: 1234" },
    { id: "bearer", type: "text", label: "Bearer token", default: "", secret: true },
    { id: "body", type: "text", label: "Body", default: "", multiline: true, placeholder: '{"hello":"world"}', showWhen: { option: "method", equals: ["POST", "PUT", "PATCH", "DELETE"] } },
    { id: "timeoutMs", type: "number", label: "Give up after", default: 15000, min: 1000, max: 60000, step: 1000, unit: "ms" },
    { id: "maxKb", type: "number", label: "Read at most", default: 1024, min: 1, max: 8192, unit: "KB" },
  ],
  "secrets-scanner": [
    {
      id: "entropy",
      type: "boolean",
      label: "Also flag high-entropy strings",
      default: true,
      help: "Catches keys no pattern matches, at the cost of also catching hashes and build ids.",
    },
    { id: "entropyThreshold", type: "number", label: "Entropy threshold", default: 4.2, min: 3, max: 6, step: 0.1, unit: "bits/char", showWhen: { option: "entropy", equals: ["true"] } },
  ],
  "readability-score-checker": [{ id: "saveReport", type: "boolean", label: "Save the full report as JSON", default: false }],

  // ---- Network (roadmap §1.9) ------------------------------------------------------------------
  "ssl-certificate-checker": [{ id: "port", type: "number", label: "Port", default: 443, min: 1, max: 65535 }],
  "http-security-header-grader": [],
  "sitemap-and-robots-validator": [
    { id: "sitemap", type: "text", label: "Sitemap URL", default: "", placeholder: "From robots.txt, or /sitemap.xml" },
  ],
  "email-mx-validator": [],
  "weather-lookup": [
    { id: "units", type: "select", label: "Units", default: "metric", choices: [choice("metric", "Celsius, km/h, mm"), choice("imperial", "Fahrenheit, mph, inches")] },
    { id: "days", type: "number", label: "Forecast", default: 5, min: 1, max: 16, unit: "days" },
  ],
};

/** Exported for the tests: the shared blocks above, so a test can assert they are wired in. */
export const EXPANSION_SHARED_OPTIONS = { packaging, pages, quality, aiMethod, delimiter, sheet } satisfies Record<
  string,
  SelectOption | TextOption | NumberOption | BooleanOption
>;
