// The agentic assistant (agent.ts), driven by a scripted "model" so nothing touches a network.
//
// What matters here is what the loop *refuses* as much as what it runs: a tool id that is not in
// the registry, a page outside the app, and a model that answers in plain prose all have to end
// in a safe, useful reply.
import { afterEach, describe, expect, it } from "vitest";
import "../index.ts";
import { runAgent, type AgentEvent } from "./agent.ts";
import { setAiFetch } from "./modelRuntime.ts";

const CREDENTIALS = { mode: "own" as const, provider: "groq", keys: { groq: "test-key" } };

/** A fake OpenAI-compatible endpoint that answers with the scripted replies, in order. */
function scripted(replies: unknown[]) {
  const seen: string[] = [];
  const restore = setAiFetch(async (_url, init) => {
    const body = JSON.parse(String((init as RequestInit).body)) as {
      messages: { role: string; content: string }[];
    };
    seen.push(body.messages[body.messages.length - 1]!.content);
    const next = replies.shift();
    const content = typeof next === "string" ? next : JSON.stringify(next);
    return new Response(JSON.stringify({ choices: [{ message: { content } }] }), {
      status: 200,
      headers: { "content-type": "application/json" },
    });
  });
  return { seen, restore };
}

async function run(request: string, replies: unknown[]) {
  const model = scripted(replies);
  const events: AgentEvent[] = [];
  try {
    await runAgent({
      request,
      files: [],
      credentials: CREDENTIALS,
      onEvent: (e) => events.push(e),
    });
  } finally {
    model.restore();
  }
  const final = events.find((e) => e.type === "final");
  return { events, final: final?.type === "final" ? final : null, seen: model.seen };
}

let restore: (() => void) | null = null;
afterEach(() => restore?.());

describe("the agentic assistant", () => {
  it("runs a registered tool, hands back its file, and reports the result", async () => {
    const { final, events } = await run("generate 2 uuids", [
      { action: "run_tool", toolId: "uuid-generator", options: { count: 2 } },
      { action: "final", message: "Here are your two UUIDs, generated by the UUID Generator." },
    ]);
    expect(events.some((e) => e.type === "step" && e.status === "done")).toBe(true);
    expect(final?.files).toHaveLength(1);
    expect(final?.outputs[0]?.toolId).toBe("uuid-generator");
    expect(final?.message).toMatch(/UUID/);
  });

  it("refuses a tool that is not in the registry and tells the model so", async () => {
    const { final, seen } = await run("do a thing", [
      { action: "run_tool", toolId: "rm-rf-everything" },
      { action: "final", message: "I could not find a tool for that, sorry about it." },
    ]);
    expect(seen.some((m) => /no available tool with id "rm-rf-everything"/.test(m))).toBe(true);
    expect(final?.files).toHaveLength(0);
  });

  it("only offers page links inside the app", async () => {
    const { final, seen } = await run("open it", [
      { action: "open_page", href: "https://evil.example/" },
      { action: "open_page", href: "/settings", label: "Open settings" },
      { action: "final", message: "Opened your settings page for you." },
    ]);
    expect(seen.some((m) => /not allowed/.test(m))).toBe(true);
    expect(final?.actions).toEqual([{ type: "navigate", href: "/settings", label: "Open settings" }]);
  });

  it("validates a workflow before offering to save it", async () => {
    const { final } = await run("make a workflow", [
      {
        action: "create_workflow",
        name: "Shrink",
        steps: [{ toolId: "pdf-to-word" }, { toolId: "compress-documents" }],
      },
      { action: "final", message: "Saved the Shrink workflow for you now." },
    ]);
    expect(final?.actions[0]).toMatchObject({ type: "save_workflow", name: "Shrink" });
  });

  it("rejects a workflow whose steps do not fit together", async () => {
    const { final, seen } = await run("bad workflow", [
      { action: "create_workflow", name: "Bad", steps: [{ toolId: "url-to-qr" }, { toolId: "merge-pdf" }] },
      { action: "final", message: "That chain does not work, so I did not save it." },
    ]);
    expect(seen.some((m) => /Invalid workflow/.test(m))).toBe(true);
    expect(final?.actions).toHaveLength(0);
  });

  it("shows a plain-prose answer instead of looping on it", async () => {
    const { final } = await run("hi", ["Hello! Ask me about OneStop."]);
    expect(final?.message).toBe("Hello! Ask me about OneStop.");
  });

  it("strips image links to files that only exist as download buttons", async () => {
    const { final } = await run("qr", [
      { action: "final", message: "Here it is:\n\n![QR](file1)\n\nEnjoy the code you asked for." },
    ]);
    expect(final?.message).not.toContain("![");
  });
});
