// Builds the bundled, offline IP -> country tables used by the phase-17 network tools
// (17-online-media-network-tools.md: "use a free-tier-compatible or self-hosted approach
// (e.g. a local GeoLite2 database) rather than a paid geolocation API").
//
// Source: the five Regional Internet Registries' own "delegated-<rir>-latest" statistics files.
// They are public, free, require no account and no key, and they are the authoritative record of
// which country each allocation was made to. Country level is all they give — that is the honest
// ceiling of a no-account dataset, and the tools say so.
//
// Country names and centroids come from mledoze/countries (ODbL), a public ISO-3166 dataset.
//
// Run: node scripts/build-geoip.mjs   (needs the Internet; the generated files are committed)
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "apps",
  "api",
  "src",
  "network",
  "data",
);

const RIRS = [
  "https://ftp.apnic.net/stats/apnic/delegated-apnic-latest",
  "https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest",
  "https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-latest",
  "https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-latest",
  "https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-latest",
];

const text = async (url) => {
  const res = await fetch(url, { headers: { "user-agent": "OneStop/0.1 geoip-build" } });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.text();
};

const v4 = [];
const v6 = [];
const ccs = new Set();

function ipv4ToInt(s) {
  const p = s.split(".").map(Number);
  return ((p[0] << 24) >>> 0) + (p[1] << 16) + (p[2] << 8) + p[3];
}

// Only the top 64 bits are kept: no RIR allocation is longer than a /64, and 8 bytes per row keeps
// the table small enough to load eagerly.
function ipv6Hi(s) {
  const [head, tail = ""] = s.split("::");
  const a = head === "" ? [] : head.split(":");
  const b = tail === "" ? [] : tail.split(":");
  const full = [...a, ...Array(Math.max(0, 8 - a.length - b.length)).fill("0"), ...b];
  let hi = 0n;
  for (let i = 0; i < 4; i++) hi = (hi << 16n) | BigInt(parseInt(full[i] || "0", 16));
  return hi;
}

for (const url of RIRS) {
  const body = await text(url);
  for (const line of body.split("\n")) {
    if (line === "" || line.startsWith("#")) continue;
    const f = line.split("|");
    if (f.length < 7) continue;
    const [, cc, type, start, value, , status] = f;
    if (cc === "" || cc === "*" || cc.length !== 2) continue;
    if (status !== "allocated" && status !== "assigned") continue;
    ccs.add(cc);
    if (type === "ipv4") {
      const s = ipv4ToInt(start);
      v4.push([s, s + Number(value) - 1, cc]);
    } else if (type === "ipv6") {
      const len = Number(value);
      if (len > 64) continue;
      const s = ipv6Hi(start);
      v6.push([s, s + (1n << BigInt(64 - len)) - 1n, cc]);
    }
  }
  console.log(`${url.split("/")[2]}: ${v4.length} v4, ${v6.length} v6 rows so far`);
}

const merge = (rows) => {
  rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  const out = [];
  for (const row of rows) {
    const last = out[out.length - 1];
    if (last && last[2] === row[2] && row[0] <= last[1] + (typeof row[0] === "bigint" ? 1n : 1)) {
      if (row[1] > last[1]) last[1] = row[1];
    } else out.push([...row]);
  }
  return out;
};

const m4 = merge(v4);
const m6 = merge(v6);
const codes = [...ccs].sort();
const index = new Map(codes.map((c, i) => [c, i]));

// Binary layout, little-endian, so a lookup is a binary search over a typed array:
//   v4: start uint32, end uint32, country uint16   (10 bytes)
//   v6: start uint64, end uint64, country uint16   (18 bytes)
const b4 = Buffer.alloc(m4.length * 10);
m4.forEach(([s, e, cc], i) => {
  b4.writeUInt32LE(s >>> 0, i * 10);
  b4.writeUInt32LE(e >>> 0, i * 10 + 4);
  b4.writeUInt16LE(index.get(cc), i * 10 + 8);
});
const b6 = Buffer.alloc(m6.length * 18);
m6.forEach(([s, e, cc], i) => {
  b6.writeBigUInt64LE(s, i * 18);
  b6.writeBigUInt64LE(e, i * 18 + 8);
  b6.writeUInt16LE(index.get(cc), i * 18 + 16);
});

await writeFile(path.join(OUT, "ipv4-country.bin"), b4);
await writeFile(path.join(OUT, "ipv6-country.bin"), b6);

const meta = await (
  await fetch("https://raw.githubusercontent.com/mledoze/countries/master/dist/countries.json")
).json();
const byCc = new Map(meta.map((c) => [c.cca2, c]));
const countries = codes.map((cc) => {
  const c = byCc.get(cc);
  return {
    cc,
    name: c?.name?.common ?? cc,
    region: c?.region ?? "",
    lat: c?.latlng?.[0] ?? null,
    lon: c?.latlng?.[1] ?? null,
  };
});

const header = `// Generated by scripts/build-geoip.mjs — do not edit by hand.
// Country codes, in the order the binary tables index them, with names, regions and centroids
// from mledoze/countries (ODbL). Regenerate with: node scripts/build-geoip.mjs
export interface CountryRow {
  cc: string;
  name: string;
  region: string;
  /** Country centroid, used when an IP can only be placed to a country. */
  lat: number | null;
  lon: number | null;
}

export const COUNTRIES: readonly CountryRow[] = ${JSON.stringify(countries, null, 0)};

export const GEOIP_BUILT_ON = ${JSON.stringify(new Date().toISOString().slice(0, 10))};
export const GEOIP_V4_ROWS = ${m4.length};
export const GEOIP_V6_ROWS = ${m6.length};
`;
await writeFile(path.join(OUT, "countries.ts"), header);
console.log(
  `v4 ${m4.length} rows (${b4.length} B), v6 ${m6.length} rows (${b6.length} B), ${codes.length} countries`,
);
